# Data Cleaning With Wine Quality White and Red

Import Laibraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Wine Quality White and Red.csv")

Head Function

In [4]:
df.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

Checking Dataframe Shape

In [5]:
df.shape

(6497, 13)

Checking Information

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6497 non-null   float64
 2   volatile acidity      6497 non-null   float64
 3   citric acid           6497 non-null   float64
 4   residual sugar        6497 non-null   float64
 5   chlorides             6497 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6497 non-null   float64
 10  sulphates             6497 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


Cheacking Uniqueness

In [7]:
df["type"].unique()

array(['white', 'red'], dtype=object)

In [8]:
df["fixed acidity"].unique()

array([ 7.  ,  6.3 ,  8.1 ,  7.2 ,  6.2 ,  8.6 ,  7.9 ,  6.6 ,  8.3 ,
        7.4 ,  6.5 ,  6.4 ,  6.8 ,  7.6 ,  6.9 ,  8.5 ,  5.8 ,  7.3 ,
        6.7 ,  6.  ,  7.1 ,  6.1 ,  7.5 ,  9.8 ,  5.5 ,  5.9 ,  7.8 ,
        5.7 ,  8.2 ,  5.6 ,  5.2 ,  8.4 , 10.2 ,  7.7 ,  5.3 ,  5.4 ,
        9.1 ,  5.  ,  8.  , 10.  ,  5.1 ,  9.2 ,  9.  ,  8.8 ,  8.7 ,
        4.8 , 10.3 ,  9.4 ,  9.6 ,  9.3 ,  8.9 ,  9.7 , 10.7 , 14.2 ,
        9.9 ,  9.5 , 11.8 ,  4.6 ,  6.15,  4.5 ,  7.15,  6.45,  4.2 ,
        4.9 ,  4.7 ,  3.8 ,  4.4 ,  3.9 , 11.2 , 10.1 , 11.5 , 12.8 ,
       11.  , 11.6 , 12.  , 15.  , 10.8 , 11.1 , 12.5 , 10.9 , 11.4 ,
       10.4 , 13.3 , 10.6 , 13.4 , 11.9 , 12.4 , 12.2 , 13.8 , 13.5 ,
       10.5 , 12.6 , 14.  , 13.7 , 12.7 , 12.3 , 15.6 , 11.3 , 13.  ,
       12.9 , 14.3 , 15.5 , 11.7 , 13.2 , 15.9 , 12.1 ])

In [9]:
df["volatile acidity"].unique()

array([0.27 , 0.3  , 0.28 , 0.23 , 0.32 , 0.22 , 0.18 , 0.16 , 0.42 ,
       0.17 , 0.48 , 0.66 , 0.34 , 0.31 , 0.26 , 0.67 , 0.25 , 0.24 ,
       0.14 , 0.12 , 0.39 , 0.33 , 0.45 , 0.46 , 0.19 , 0.2  , 0.21 ,
       0.38 , 0.47 , 0.35 , 0.54 , 0.43 , 0.44 , 0.265, 0.36 , 0.305,
       0.13 , 0.41 , 0.485, 0.425, 0.37 , 0.255, 0.595, 0.29 , 0.53 ,
       0.15 , 0.57 , 0.4  , 0.245, 0.685, 0.495, 0.64 , 0.52 , 0.115,
       0.58 , 0.585, 0.59 , 0.6  , 0.55 , 0.125, 0.1  , 0.145, 0.335,
       0.365, 0.905, 0.49 , 0.155, 0.51 , 0.62 , 0.345, 0.475, 0.56 ,
       0.235, 0.105, 0.5  , 0.11 , 0.225, 0.395, 0.655, 0.205, 0.415,
       0.705, 0.08 , 0.68 , 0.275, 0.61 , 0.135, 0.165, 0.85 , 0.185,
       0.325, 0.445, 0.545, 0.91 , 0.71 , 1.005, 0.385, 0.76 , 0.93 ,
       0.295, 0.695, 0.815, 0.285, 0.175, 0.615, 0.315, 0.965, 0.375,
       0.74 , 0.78 , 0.215, 0.435, 0.75 , 0.085, 0.73 , 0.65 , 0.455,
       1.1  , 0.555, 0.09 , 0.63 , 0.69 , 0.785, 0.405, 0.355, 0.7  ,
       0.88 , 0.645,

In [10]:
df["citric acid"].unique()

array([0.36, 0.34, 0.4 , 0.32, 0.16, 0.43, 0.41, 0.37, 0.62, 0.38, 0.04,
       0.48, 0.42, 0.14, 0.35, 0.39, 0.2 , 0.23, 0.26, 0.27, 0.31, 0.25,
       0.29, 0.33, 0.59, 0.15, 0.24, 0.07, 0.03, 0.13, 0.28, 0.46, 0.3 ,
       0.61, 0.63, 0.66, 0.54, 0.5 , 0.  , 0.47, 0.56, 0.22, 0.67, 0.18,
       0.45, 0.44, 0.88, 0.21, 0.08, 0.49, 0.58, 0.7 , 0.6 , 0.51, 0.1 ,
       0.19, 0.12, 0.09, 0.53, 0.02, 0.65, 0.17, 0.71, 0.06, 0.68, 0.72,
       0.69, 1.66, 0.57, 0.05, 0.52, 1.  , 0.01, 0.74, 0.81, 0.55, 0.64,
       0.73, 0.99, 0.78, 0.79, 0.82, 0.8 , 1.23, 0.86, 0.11, 0.91, 0.76,
       0.75])

In [11]:
df["residual sugar"].unique()

array([20.7 ,  1.6 ,  6.9 ,  8.5 ,  7.  ,  1.5 ,  1.45,  4.2 ,  1.2 ,
       19.25,  1.1 ,  7.5 ,  2.9 ,  1.7 ,  1.3 ,  9.  ,  1.  ,  8.7 ,
        2.  , 10.4 ,  2.05, 14.95,  5.4 , 17.95,  2.5 ,  7.4 ,  1.4 ,
        4.4 ,  5.  ,  0.9 , 11.9 , 12.4 ,  4.6 ,  4.9 ,  6.4 ,  2.1 ,
       10.1 ,  7.8 ,  4.8 ,  8.8 , 16.  ,  6.1 ,  8.2 , 11.8 , 11.  ,
       13.3 ,  1.8 , 15.9 , 10.5 , 13.5 ,  9.6 , 12.1 , 18.9 , 14.4 ,
       16.5 , 18.75,  9.2 ,  3.3 ,  5.7 , 12.2 ,  6.85,  7.6 ,  2.8 ,
        2.7 , 13.1 , 15.8 ,  8.1 , 15.7 ,  1.9 ,  2.2 ,  4.3 ,  5.2 ,
        4.1 ,  8.  , 10.2 , 14.  , 14.5 , 13.  ,  2.4 ,  8.95,  9.85,
        0.8 ,  4.55, 17.7 ,  5.1 , 12.9 ,  5.5 , 22.  ,  9.4 ,  3.8 ,
        3.6 ,  3.5 , 16.1 , 13.2 , 13.9 ,  2.3 , 11.6 ,  8.3 ,  6.2 ,
        9.7 ,  5.3 , 17.5 ,  9.5 , 17.8 , 10.3 , 14.3 , 15.55, 13.7 ,
       11.2 , 16.2 , 19.45, 13.6 ,  7.1 , 10.7 ,  8.9 ,  9.1 ,  4.7 ,
       15.6 , 15.4 ,  7.2 , 14.2 ,  5.8 , 19.8 ,  7.3 , 10.6 , 11.3 ,
        6.8 ,  6.7 ,

In [12]:
df["chlorides"].unique()

array([0.045, 0.049, 0.05 , 0.058, 0.044, 0.033, 0.035, 0.04 , 0.032,
       0.046, 0.029, 0.038, 0.074, 0.052, 0.051, 0.047, 0.042, 0.08 ,
       0.053, 0.057, 0.172, 0.173, 0.069, 0.06 , 0.063, 0.066, 0.067,
       0.062, 0.068, 0.147, 0.039, 0.043, 0.048, 0.092, 0.064, 0.041,
       0.056, 0.061, 0.054, 0.034, 0.059, 0.082, 0.065, 0.026, 0.02 ,
       0.036, 0.027, 0.037, 0.055, 0.2  , 0.197, 0.03 , 0.07 , 0.031,
       0.132, 0.071, 0.028, 0.089, 0.021, 0.108, 0.022, 0.081, 0.023,
       0.073, 0.346, 0.025, 0.09 , 0.114, 0.186, 0.18 , 0.084, 0.083,
       0.096, 0.094, 0.24 , 0.29 , 0.185, 0.024, 0.11 , 0.078, 0.13 ,
       0.135, 0.115, 0.072, 0.17 , 0.018, 0.119, 0.126, 0.017, 0.019,
       0.15 , 0.152, 0.088, 0.244, 0.137, 0.093, 0.077, 0.079, 0.076,
       0.201, 0.301, 0.138, 0.169, 0.168, 0.122, 0.167, 0.239, 0.123,
       0.133, 0.211, 0.255, 0.204, 0.208, 0.086, 0.16 , 0.179, 0.087,
       0.217, 0.157, 0.148, 0.158, 0.099, 0.085, 0.091, 0.095, 0.142,
       0.075, 0.121,

In [13]:
df["free sulfur dioxide"].unique()

array([ 45. ,  14. ,  30. ,  47. ,  28. ,  11. ,  17. ,  16. ,  48. ,
        41. ,  29. ,  34. ,  19. ,  25. ,  56. ,  35. ,  32. ,  37. ,
        20. ,   7. ,  31. ,  43. ,  22. ,  21. ,  38. ,  63. ,  33. ,
        62. ,  39. ,  50. ,  44. ,  27. ,  81. ,  50.5,   9. ,  26. ,
        51. ,  42. ,  54. ,  52. ,  55. ,  69. ,  65. ,  15. ,   4. ,
        64. ,  60. ,  68. ,   8. ,  57. ,  40. ,  46. ,  59. ,  36. ,
        49. ,  18. ,  24. ,  53. ,  23. ,  58. ,  12. ,  72. ,   5. ,
        61. ,  66. ,  75. ,  76. ,  64.5,   3. ,  82. ,  10. , 131. ,
        38.5,  82.5,  13. ,  87. ,  73.5,  83. ,  67. ,  79. ,  70. ,
         6. ,  77. , 122.5,  78. ,  11.5,  80. ,  44.5,  35.5,  73. ,
        71. ,  15.5,  88. ,  77.5,  41.5, 118.5,  96. ,  52.5, 146.5,
        48.5, 128. , 110. ,  42.5,  40.5,  39.5,  19.5,  85. ,  74. ,
        89. ,  86. ,  93. ,  30.5, 138.5,  95. , 124. , 105. , 101. ,
       108. ,   2. ,  79.5,  61.5,  98. , 112. ,  51.5,  70.5,  23.5,
        59.5,  28.5,

In [14]:
df["total sulfur dioxide"].unique()

array([170. , 132. ,  97. , 186. , 136. , 129. ,  63. , 109. ,  75. ,
       143. , 172. , 112. ,  99. , 171. , 133. , 102. , 122. , 168. ,
       142. , 245. , 146. , 141. , 114. ,  47. , 100. , 117. , 179. ,
       123. , 149. , 138. , 158. , 157. , 160. , 152. , 154. , 167. ,
       206. , 207. , 150. , 173. , 124. ,  82. , 108. , 191. , 213. ,
       147. ,  78. , 111. , 151. , 120. , 174. ,  96. , 105. , 244. ,
       238.5, 201. ,  72. ,  87. ,  69. , 103. , 166. , 164. , 155. ,
       156. , 202. , 243. , 148. , 240. ,  80. ,  83. , 192. , 162. ,
       187. , 163. , 255. , 195. ,  85. , 196. , 131. , 126. , 203. ,
       184. ,  57. , 241. , 188. , 121. ,  79. ,  77. , 107. , 116. ,
       135. ,  76. , 198. , 119. , 159. , 205. , 177. , 197. ,  98. ,
       110. , 130. ,  65. , 176. , 183. , 227. , 226. , 230. , 210. ,
       211. , 125. , 181. , 180. , 214. , 204. , 236. , 134. , 153. ,
        68. , 161. , 144. , 140. , 145. , 200. , 272. , 194. , 208. ,
       221. ,  90. ,

In [15]:
df["density"].unique()

array([1.001   , 0.994   , 0.9951  , 0.9956  , 0.9949  , 0.9938  ,
       0.9908  , 0.9947  , 0.992   , 0.9912  , 1.0002  , 0.9914  ,
       0.9928  , 0.9892  , 0.9917  , 0.9955  , 0.993   , 0.9937  ,
       0.9961  , 0.9906  , 0.9974  , 0.9934  , 0.9939  , 0.9962  ,
       0.9905  , 0.9999  , 0.9954  , 0.9931  , 0.995   , 0.991   ,
       0.9911  , 0.9972  , 0.9926  , 0.9927  , 0.9903  , 0.9958  ,
       0.9964  , 0.9941  , 0.9898  , 0.9929  , 0.9985  , 0.9946  ,
       0.9966  , 0.9975  , 0.9957  , 0.99    , 0.9899  , 0.9916  ,
       0.9969  , 0.9979  , 0.9913  , 0.997   , 1.      , 0.999   ,
       0.9959  , 0.9982  , 0.9968  , 0.9984  , 0.9952  , 0.9924  ,
       0.9923  , 0.9921  , 0.9918  , 0.9919  , 0.9894  , 0.998   ,
       0.9932  , 0.9896  , 0.9902  , 0.9936  , 0.9942  , 0.9973  ,
       0.9944  , 0.9989  , 0.9971  , 0.9998  , 0.9976  , 0.996   ,
       0.9935  , 0.9904  , 0.9996  , 0.9977  , 0.9965  , 0.9945  ,
       0.9915  , 0.9909  , 0.9988  , 0.9978  , 0.9933  , 0.994

In [16]:
df["pH"].unique()

array([3.  , 3.3 , 3.26, 3.19, 3.18, 3.22, 2.99, 3.14, 3.54, 2.98, 3.25,
       3.24, 3.33, 3.12, 3.17, 3.47, 3.05, 3.42, 3.45, 3.38, 3.1 , 3.2 ,
       3.37, 3.13, 3.21, 3.11, 3.16, 3.27, 3.36, 3.35, 3.34, 3.32, 3.31,
       3.09, 3.03, 3.02, 3.15, 3.69, 2.95, 2.94, 3.39, 3.04, 2.89, 3.4 ,
       3.01, 3.63, 3.29, 3.23, 3.28, 3.06, 3.08, 2.87, 2.93, 3.44, 3.5 ,
       3.48, 3.72, 3.53, 3.52, 2.96, 3.61, 3.43, 3.49, 3.51, 3.46, 3.07,
       2.97, 3.41, 3.64, 3.56, 2.86, 2.88, 2.85, 3.58, 3.55, 3.66, 3.59,
       2.74, 2.92, 3.82, 3.81, 3.65, 2.9 , 3.77, 2.91, 3.62, 3.74, 2.8 ,
       3.6 , 2.72, 2.79, 3.57, 3.8 , 3.68, 2.77, 3.79, 3.7 , 2.84, 3.76,
       2.83, 3.75, 2.82, 3.67, 3.9 , 3.85, 3.71, 3.78, 4.01])

In [17]:
df["sulphates"].unique()

array([0.45, 0.49, 0.44, 0.4 , 0.47, 0.56, 0.53, 0.63, 0.52, 0.67, 0.55,
       0.36, 0.39, 0.5 , 0.35, 0.48, 0.51, 0.71, 0.37, 0.42, 0.28, 0.34,
       0.46, 0.58, 0.38, 0.54, 0.64, 0.6 , 0.65, 0.77, 0.41, 0.3 , 0.59,
       0.57, 0.43, 0.32, 0.84, 0.33, 0.29, 0.27, 0.68, 0.66, 0.61, 0.74,
       0.79, 0.7 , 0.62, 0.85, 0.76, 0.75, 0.78, 0.69, 0.72, 0.73, 0.96,
       0.97, 0.82, 0.95, 0.9 , 0.88, 0.31, 0.25, 0.8 , 0.87, 0.86, 0.81,
       0.92, 0.26, 0.98, 1.06, 1.  , 0.89, 0.94, 0.99, 0.22, 0.23, 0.83,
       1.01, 1.08, 1.56, 0.93, 1.28, 0.91, 1.2 , 1.12, 1.14, 1.95, 1.22,
       1.98, 1.31, 2.  , 1.59, 1.02, 1.03, 1.61, 1.09, 1.26, 1.36, 1.18,
       1.13, 1.04, 1.11, 1.07, 1.05, 1.17, 1.62, 1.34, 1.16, 1.1 , 1.15,
       1.33])

In [18]:
df["alcohol"].unique()

array([ 8.8       ,  9.5       , 10.1       ,  9.9       ,  9.6       ,
       11.        , 12.        ,  9.7       , 10.8       , 12.4       ,
       11.4       , 12.8       , 11.3       , 10.5       ,  9.3       ,
       10.        , 10.4       , 11.6       , 12.3       , 10.2       ,
        9.        , 11.2       ,  8.6       ,  9.4       ,  9.8       ,
       11.7       , 10.9       ,  9.1       ,  8.9       , 10.3       ,
       12.6       , 10.7       , 12.7       , 10.6       ,  9.2       ,
        8.7       , 11.5       , 11.8       , 12.1       , 11.1       ,
        8.5       , 12.5       , 11.9       , 12.2       , 12.9       ,
       13.9       , 14.        , 13.5       , 13.3       , 13.2       ,
       13.7       , 13.4       , 13.        ,  8.        , 13.1       ,
       13.6       ,  8.4       , 14.2       , 11.94      , 12.89333333,
       11.46666667, 10.98      , 10.03333333, 11.43333333, 10.53333333,
        9.53333333, 10.93333333, 11.36666667, 11.33333333, 11.06

In [19]:
df["quality"].unique()

array([6, 5, 7, 8, 4, 3, 9])

Checking Null Values

In [20]:
df.isnull().sum()

type                    0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

Checking Duplicate Values

In [21]:
df.duplicated().sum()

1177

Removing Duplicate Values

In [23]:
df.drop_duplicates(inplace = True)

Rechecking Duplicate Values

In [24]:
df.duplicated().sum()

0

Checking Description

In [25]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    5320.000000       5320.000000  5320.000000     5320.000000   
mean        7.215179          0.344130     0.318494        5.048477   
std         1.319671          0.168248     0.147157        4.500180   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.240000        1.800000   
50%         7.000000          0.300000     0.310000        2.700000   
75%         7.700000          0.410000     0.400000        7.500000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  5320.000000          5320.000000           5320.000000  5320.000000   
mean      0.056690            30.036654            114.109023     0.994535   
std       0.036863            17.805045             56.774223     0.002966   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            16.000000             74.000000     0.992200   
50%       0.047000            28.000000            116.000000     0.994650   
75%       0.066000            41.000000            153.250000     0.996770   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  5320.000000  5320.000000  5320.000000  5320.000000  
mean      3.224664     0.533357    10.549241     5.795677  
std       0.160379     0.149743     1.185933     0.879772  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.400000     6.000000  
75%       3.330000     0.600000    11.400000     6.000000  
max       4.010000     2.000000    14.900000     9.000000